@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center text-center">
        <div class="col-md-8">
            <div class="card">

                <div class="card-body">
                    {{-- About Page Content Complete  --}}
                    <h1>Terms and Conditions</h1>
                    <p>
                        Welcome to farmfresh.com. Farm Fresh and its affiliates provide access to the farmfresh.com website the “website” to you subject to the conditions set out on this page.
                    </p>

                    <p>
                        Please read these conditions carefully before using the farmfresh.com website. By using the farmfresh.com website, you signify your agreement to be bound by these conditions.
                    </p>

                    <p>
                        In addition, when you use any current or future farmfresh.com service eg. Wish List or Marketplace, you will also be subject to the terms, guidelines and conditions applicable to that farmfresh Service. “Terms”. If these Conditions of Use are inconsistent with such Terms, the Terms will control.
                    </p>

                    <p>
                        These “Conditions of Use” constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                    </p>

                    <p>
                        Conditions Relating to Your Use of farmfresh.com
                    </p>
                    <p>
                        Notice and Procedure for Making Claims of Infringement
                    </p>
                    <p>
                        Notice and Procedure for Notifying farmfresh.com of Objectionable Content
                    </p>
                    </div>
        </div>
    </div>
</div>
@endsection