@extends('layouts.app')

@section('content')
<div class="max-container my-4">
    <div class="row justify-content-center">
        <div class="">
            <div class="card">

                <div class="card-body">
                    {{-- About Page Content Complete --}}
                    <div class="static-page-head">
                        <img src="images/TermsAndConditions.png" alt="">
                        <h1>Terms and Conditions</h1>
                    </div>
                    <div class="m-4">
                        <p>
                            Welcome to farmfresh.com. Farm Fresh and its affiliates provide access to the farmfresh.com
                            website the “website” to you subject to the conditions set out on this page.
                        </p>

                        <p>
                            Please read these conditions carefully before using the farmfresh.com website. By using the
                            farmfresh.com website, you signify your agreement to be bound by these conditions.
                        </p>

                        <p>
                            In addition, when you use any current or future farmfresh.com service eg. Wish List or
                            Marketplace, you will also be subject to the terms, guidelines and conditions applicable to that
                            farmfresh Service. “Terms”. If these Conditions of Use are inconsistent with such Terms, the
                            Terms will control.
                        </p>

                        <p>
                            These “Conditions of Use” constitute an electronic record within the meaning of the applicable
                            law. This electronic record is generated by a computer system and does not require any physical
                            or digital signatures.
                        </p>

                        <ul>
                            <li>
                                Conditions Relating to Your Use of farmfresh.com
                            </li>
                            <li>
                                Notice and Procedure for Making Claims of Infringement
                            </li>
                            <li>
                                Notice and Procedure for Notifying farmfresh.com of Objectionable Content
                            </li>
                        </ul>
                        <h3 class="mt-4">Conditions Relating to Your Use of farmfresh.com</h3>
                        <p>
                            If you use the website, you are responsible for maintaining the confidentiality of your account
                            and password and for restricting access to your computer to prevent unauthorised access to your
                            account. You agree to accept responsibility for all activities that occur under your account or
                            password. You should take all necessary steps to ensure that the password is kept confidential
                            and secure and should inform us immediately if you have any reason to believe that your password
                            has become known to anyone else, or if the password is being, or is likely to be, used in an
                            unauthorised manner. Please ensure that the details you provide us with are correct and complete
                            and inform us immediately of any changes to the information that you provided when registering.
                            You can access and update much of the information you provided us with in the Your Account area
                            of the website. You agree and acknowledge that you will use your account on the website to
                            purchase products only for your personal use and not for business purposes. Should you wish to
                            order products for business purposes, please create a vendor account on farmfresh.com.
                        </p>
                        <h4 class="mt-4">Privacy</h4>
                        <p>
                            Please review our Privacy Notice, which also governs your visit to farmfresh.com, to understand our
                            practices. The personal information / data provided to us by you during the course of usage of
                            farmfresh.com will be treated as strictly confidential and in accordance with the Privacy Notice and
                            applicable laws and regulations. If you object to your information being transferred or used, please
                            do not use the website.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection